version: '3.3'


services:

  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    env_file:
      - postgres.env
    networks:
      - intranet
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
      - bkpdb:/opt/backups

  pgadmin:
    container_name: pgadmin
    depends_on:
      - postgres
    env_file:
      - pgadmin.env
    image: dpage/pgadmin4
    links:
      - postgres
    networks:
      - intranet
    ports:
      - "8080:80"
    restart: always
    volumes:
      - pg:/var/lib/pgadmin


volumes:
  db:
  bkpdb:
  pg:


networks:
  intranet:
    driver: bridge
